### ISSUE TITLE
%link% variable is rendered once only.

### ISSUE THREAD

**Issue by ashecret** [bcomeau/parse-server-mailgun-adapter-template#8]
If `%link%` variable is used in more than one places, let's say one in a link button and one as plain text in a paragraph, it's rendered in the first place only. I have tried switching places and using other html attributes.

**Comment by alsoft-alex** [comment]
My problem, too. It is because the replace function replaces only the first occurrence of a string. 

The issue could easily be solved like this:

function fillVariables(text, options) {
    text = text.split("%username%").join(options.user.get("username"));
    text = text.split("%email%").join(options.user.get("email"));
    text = text.split("%appname%").join(options.appName);
    text = text.split("% link%").join(options.link);
    return text;
  }

**Comment by bcomeau** [comment]
Fixed in PR #9

**Comment by alsoft-alex** [comment]
Merci, c'était rapide :-)
